<?php

/**
 * Cafe Francois
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maulit@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Cafe Francois
 * @version 1.0.0
 */

$app->get('/', function () use ($app) {
    return $app->version();
});

/**
 * POST createItem
 * Summary: Create an item
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->POST('//item', 'ItemApi@createItem');
/**
 * PUT updateItem
 * Summary: Update an existing item
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->PUT('//item', 'ItemApi@updateItem');
/**
 * DELETE deleteItem
 * Summary: Deletes an Item
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->DELETE('//item/{itemId}', 'ItemApi@deleteItem');
/**
 * GET getItemById
 * Summary: Find item by ID
 * Notes: Returns a single item
 * Output-Formats: [application/json]
 */
$app->GET('//item/{itemId}', 'ItemApi@getItemById');
/**
 * PUT updateItemWithForm
 * Summary: Updates an item in the store with form data
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->PUT('//item/{itemId}', 'ItemApi@updateItemWithForm');
/**
 * POST createOrder
 * Summary: Create an order
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->POST('//order', 'OrderApi@createOrder');
/**
 * PUT updateOrder
 * Summary: Update an existing order
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->PUT('//order', 'OrderApi@updateOrder');
/**
 * GET findOrdersByStatus
 * Summary: Finds Orders by status
 * Notes: Multiple status values can be provided with comma separated strings
 * Output-Formats: [application/json]
 */
$app->GET('//order/findByStatus', 'OrderApi@findOrdersByStatus');
/**
 * DELETE deleteOrder
 * Summary: Deletes an Order
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->DELETE('//order/{orderId}', 'OrderApi@deleteOrder');
/**
 * GET getOrderById
 * Summary: Find order by ID
 * Notes: Returns a single order
 * Output-Formats: [application/json]
 */
$app->GET('//order/{orderId}', 'OrderApi@getOrderById');
/**
 * PUT updateOrderWithForm
 * Summary: Updates an order in the store with form data
 * Notes: 
 * Output-Formats: [application/json]
 */
$app->PUT('//order/{orderId}', 'OrderApi@updateOrderWithForm');

